Intalling the techno files for gf180mcu_c4m from CRL.
lip6/coriolis pull request #73
Opened 2023-10-20 09:02 UTC by jpc-lip6

2023-10-20 09:45 UTC, robtaylor approved these changes

2023-10-25 22:14 UTC, robtaylor requested changes
This seems to clash with #76

2023-10-25 22:14 UTC, robtaylor commented on cumulus/src/designflow/technos.py
> +
alliance as a dependency?

2023-10-25 22:14 UTC, robtaylor commented on cumulus/src/designflow/technos.py
> +            break
alliance a dependency?

2024-01-22 14:31 UTC, closed without merging

2024-01-22 14:32 UTC, jpc-lip6 commented
This should have be already integrated trough the merge of ``rebase-analog-fixes``